name: ptc_quiz1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  intl: ^0.19.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  faker: ^2.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  